version: '3.7'
services:
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: yuadhistra
      MINIO_ROOT_PASSWORD: Dt_backend#2024
    volumes:
      - '/Users/yuadhistra/Documents/MinIo Bucket:/data'
    command: server /data
